// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace GreenEnergyHub.Charges.QueryApi.ScaffoldedModels
{
    public partial class ChargeOperation
    {
        public ChargeOperation()
        {
            ChargePeriodDetails = new HashSet<ChargePeriodDetails>();
            ChargePrice = new HashSet<ChargePrice>();
        }

        public Guid Id { get; set; }
        public Guid ChargeId { get; set; }
        public string CorrelationId { get; set; }
        public string ChargeOperationId { get; set; }
        public DateTime WriteDateTime { get; set; }

        public virtual Charge Charge { get; set; }
        public virtual ICollection<ChargePeriodDetails> ChargePeriodDetails { get; set; }
        public virtual ICollection<ChargePrice> ChargePrice { get; set; }
    }
}