// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace GreenEnergyHub.Charges.QueryApi.ScaffoldedModels
{
    public partial class ChargeLinkPeriodDetails
    {
        public Guid Id { get; set; }
        public Guid ChargeLinkId { get; set; }
        public DateTime StartDateTime { get; set; }
        public DateTime EndDateTime { get; set; }
        public int Factor { get; set; }
        public Guid CreatedByOperationId { get; set; }
        public Guid? RetiredByOperationId { get; set; }

        public virtual ChargeLink ChargeLink { get; set; }
        public virtual ChargeLinkOperation CreatedByOperation { get; set; }
        public virtual ChargeLinkOperation RetiredByOperation { get; set; }
    }
}