// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace GreenEnergyHub.Charges.QueryApi.ScaffoldedModels
{
    public partial class ChargeLinkOperation
    {
        public ChargeLinkOperation()
        {
            ChargeLinkPeriodDetailsCreatedByOperation = new HashSet<ChargeLinkPeriodDetails>();
            ChargeLinkPeriodDetailsRetiredByOperation = new HashSet<ChargeLinkPeriodDetails>();
        }

        public Guid Id { get; set; }
        public Guid ChargeLinkId { get; set; }
        public string CorrelationId { get; set; }
        public string SenderProvidedId { get; set; }
        public DateTime WriteDateTime { get; set; }

        public virtual ChargeLink ChargeLink { get; set; }
        public virtual ICollection<ChargeLinkPeriodDetails> ChargeLinkPeriodDetailsCreatedByOperation { get; set; }
        public virtual ICollection<ChargeLinkPeriodDetails> ChargeLinkPeriodDetailsRetiredByOperation { get; set; }
    }
}