// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace GreenEnergyHub.Charges.QueryApi.ScaffoldedModels
{
    public partial class ChargeLink
    {
        public ChargeLink()
        {
            ChargeLinkOperation = new HashSet<ChargeLinkOperation>();
            ChargeLinkPeriodDetails = new HashSet<ChargeLinkPeriodDetails>();
        }

        public Guid Id { get; set; }
        public Guid ChargeId { get; set; }
        public Guid MeteringPointId { get; set; }

        public virtual Charge Charge { get; set; }
        public virtual MeteringPoint MeteringPoint { get; set; }
        public virtual ICollection<ChargeLinkOperation> ChargeLinkOperation { get; set; }
        public virtual ICollection<ChargeLinkPeriodDetails> ChargeLinkPeriodDetails { get; set; }
    }
}