// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace GreenEnergyHub.Charges.QueryApi.ScaffoldedModels
{
    public partial class Charge
    {
        public Charge()
        {
            ChargeLink = new HashSet<ChargeLink>();
            ChargeOperation = new HashSet<ChargeOperation>();
            ChargePeriodDetails = new HashSet<ChargePeriodDetails>();
            ChargePrice = new HashSet<ChargePrice>();
            DefaultChargeLink = new HashSet<DefaultChargeLink>();
        }

        public Guid Id { get; set; }
        public string SenderProvidedChargeId { get; set; }
        public int ChargeType { get; set; }
        public Guid MarketParticipantId { get; set; }
        public bool TaxIndicator { get; set; }
        public int Resolution { get; set; }
        public string Currency { get; set; }
        public bool TransparentInvoicing { get; set; }

        public virtual MarketParticipant MarketParticipant { get; set; }
        public virtual ICollection<ChargeLink> ChargeLink { get; set; }
        public virtual ICollection<ChargeOperation> ChargeOperation { get; set; }
        public virtual ICollection<ChargePeriodDetails> ChargePeriodDetails { get; set; }
        public virtual ICollection<ChargePrice> ChargePrice { get; set; }
        public virtual ICollection<DefaultChargeLink> DefaultChargeLink { get; set; }
   }
}
