// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace GreenEnergyHub.Charges.QueryApi.ScaffoldedModels
{
    public partial class MarketParticipant
    {
        public MarketParticipant()
        {
            Charge = new HashSet<Charge>();
        }

        public Guid Id { get; set; }
        public string MarketParticipantId { get; set; }
        public string Name { get; set; }
        public int Role { get; set; }

        public virtual ICollection<Charge> Charge { get; set; }
    }
}