# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  #
  # Detect changes to start relevant jobs
  #

  changes:
    uses: ./.github/workflows/detect-changes.yml

  #
  # CD Infrastructure
  #

  infrastructure_promote_prerelease:
    needs: changes
    if: ${{ needs.changes.outputs.infrastructure == 'true' }}
    uses: Energinet-DataHub/.github/.github/workflows/promote-prerelease.yml@v8
    with:
      RELEASE_NAME_PREFIX: infrastructure

  #
  # CD .NET
  #

  # dotnet_update_coverage_report:
  #   needs: changes
  #   if: ${{ needs.changes.outputs.dotnet == 'true' }}
  #   uses: Energinet-DataHub/.github/.github/workflows/dotnet-solution-ci.yml@v8
  #   with:
  #     SOLUTION_FILE_PATH: 'source/GreenEnergyHub.Charges/GreenEnergyHub.Charges.sln'
  #     USE_AZURE_FUNCTIONS_TOOLS: true
  #     ENVIRONMENT: AzureAuth
  #   secrets:
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     AZURE_SPN_ID: ${{ secrets.AZURE_SPN_ID_OIDC }}
  #     AZURE_KEYVAULT_URL: ${{ secrets.AZURE_KEYVAULT_URL }}
  #     AZURE_SECRETS_KEYVAULT_URL: ${{ secrets.AZURE_SECRETS_KEYVAULT_URL }}

  # dotnet_promote_prerelease:
  #   needs: changes
  #   if: ${{ needs.changes.outputs.dotnet == 'true' }}
  #   uses: Energinet-DataHub/.github/.github/workflows/promote-prerelease.yml@v8
  #   with:
  #     RELEASE_NAME_PREFIX: dotnet

  #
  # Dispatch deployment request
  #

  dispatch_deploment_event:
    runs-on: ubuntu-latest
    needs: [
      # DO NOT REMOVE: necessary to create client-payload
      changes,
      # Infrastructure
      infrastructure_promote_prerelease,
      # .NET
      # dotnet_promote_prerelease,
    ]
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled') &&
      !(
        needs.infrastructure_promote_prerelease.result == 'skipped' &&
        needs.dotnet_promote_prerelease.result == 'skipped'
      )
    steps:
      - run: echo "${{ toJSON(needs) }}"

      - name: Find associated PR
        uses: jwalton/gh-find-current-pr@v1
        id: find_pull_request
        with:
          state: all

      - name: Fail if PR not found
        if: steps.find_pull_request.outputs.pr == ''
        run: exit 1

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: '${{ secrets.ENVIRONMENT_REPOSITORY_PATH }}'
          event-type: 'geh-charges-deployment-request-domain'
          client-payload: '{"pr": "${{ steps.find_pull_request.outputs.pr }}", "infrastructure_deploy": "${{ needs.changes.outputs.infrastructure }}", "dotnet_deploy": "${{ needs.changes.outputs.dotnet }}"}'
