# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci_base:
    uses: Energinet-DataHub/.github/.github/workflows/ci-base.yml@1.13.0
  
  dotnet_solution_ci:
    uses: Energinet-DataHub/geh-charges/.github/workflows/dotnet-solution-ci.yml@1.13.0
    with:
      SOLUTION_FILE_PATH: 'source/GreenEnergyHub.Charges/GreenEnergyHub.Charges.sln'
    secrets:
      AZURE_KEYVAULT_URL: ${{ secrets.AZURE_KEYVAULT_URL }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_RG_NAME: ${{ secrets.AZURE_RG_NAME }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SPN_ID: ${{ secrets.AZURE_SPN_ID }}
      AZURE_SPN_SECRET: ${{ secrets.AZURE_SPN_SECRET }}
      AZURE_APPI_INSTRUMENTATION_KEY: ${{ secrets.AZURE_APPI_INSTRUMENTATION_KEY }}
      AZURE_SB_CONNECTION_STRING: ${{ secrets.AZURE_SB_CONNECTION_STRING }}

  terraform_validate:
    uses: Energinet-DataHub/.github/.github/workflows/terraform-validate.yml@1.13.0
    with:
      TERRAFORM_WORKING_DIR_PATH: './build/infrastructure/main'
      TERRAFORM_VERSION: '1.0.10'

  functionhost_ci:
    needs: [ci_base, terraform_validate]
    uses: Energinet-DataHub/.github/.github/workflows/dotnet-create-function-artifact.yml@1.13.0
    with:
      CSPROJ_FILE_PATH: 'source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/GreenEnergyHub.Charges.FunctionHost.csproj'
      DOTNET_VERSION: '5.0.202'
      ARTIFACT_NAME: functionhost

  database_migration_ci:
    needs: [ci_base, terraform_validate]
    uses: Energinet-DataHub/.github/.github/workflows/dotnet-create-function-artifact.yml@1.13.0
    with:
      CSPROJ_FILE_PATH: 'source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/GreenEnergyHub.Charges.ApplyDBMigrationsApp.csproj'
      DOTNET_VERSION: '5.0.202'
      ARTIFACT_NAME: databasemigration

  create_prerelease:
    needs: [
      functionhost_ci,
      database_migration_ci
    ]
    uses: Energinet-DataHub/.github/.github/workflows/create-prerelease.yml@1.13.0
    with:
      CALLER_REPOSITORY_PATH: Energinet-DataHub/geh-charges
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}