# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci_base:
    uses: Energinet-DataHub/.github/.github/workflows/ci-base.yml@1.13.0

  terraform_validate:
    uses: Energinet-DataHub/.github/.github/workflows/terraform-validate.yml@1.13.0
    with:
      TERRAFORM_WORKING_DIR_PATH: './build/infrastructure/main'
      TERRAFORM_VERSION: '1.0.6'

  clients_ci:
    uses: Energinet-DataHub/geh-charges/.github/workflows/clients-ci.yml@renetnielsen/new-sub

  functionhost_ci:
    uses: Energinet-DataHub/geh-charges/.github/workflows/functionhost-ci.yml@renetnielsen/new-sub

  create_prerelease:
    needs: [ci_base, terraform_validate]
    uses: Energinet-DataHub/.github/.github/workflows/create-prerelease.yml@1.13.0
    with:
      REMOTE_REPOSITORY_PATH: Energinet-DataHub/geh-charges
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}