# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: .NET solution CI

on:
  workflow_call:
    inputs:
      SOLUTION_FILE_PATH:
        required: true
        type: string
    secrets:
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_RG_NAME:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SPN_ID:
        required: true
      AZURE_SPN_SECRET:
        required: true
      AZURE_APPI_INSTRUMENTATION_KEY:
        required: true
      AZURE_SB_CONNECTION_STRING:
        required: true
        
jobs:
  function_ci:
    environment: CI
    env:
      AZURITE_VERSION: '3.14.0'
      DOTNET_VERSION: '5.0.202'
      AZURE_FUNCTIONS_CORE_TOOLS_VERSION: '3.0.3568'
      # Variables necessary to manage Azure resources for tests (similar to local use of 'integrationtest.local.settings.json')
      SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RG_NAME }}
      DEFAULT_LOCATION: 'westeurope'
      TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      CLIENT_ID: ${{ secrets.AZURE_SPN_ID }}
      CLIENT_SECRET: ${{ secrets.AZURE_SPN_SECRET }} 
      # Variables necessary to start function for tests (similar to local use of 'local.settings.json')
      APPINSIGHTS_INSTRUMENTATIONKEY: ${{ secrets.AZURE_APPI_INSTRUMENTATION_KEY }}
      INTEGRATIONEVENT_SENDER_CONNECTION_STRING: ${{ secrets.AZURE_SB_CONNECTION_STRING }}
      INTEGRATIONEVENT_LISTENER_CONNECTION_STRING: ${{ secrets.AZURE_SB_CONNECTION_STRING }}
      DOMAINEVENT_SENDER_CONNECTION_STRING: ${{ secrets.AZURE_SB_CONNECTION_STRING }}
      DOMAINEVENT_LISTENER_CONNECTION_STRING: ${{ secrets.AZURE_SB_CONNECTION_STRING }}
      # Variables that overrides settings in 'functionhost.settings.json'
      FunctionAppHostPath: 'C:\npm\prefix\node_modules\azure-functions-core-tools\bin\func.dll'
      FunctionApplicationPath: '..\\..\\..\\..\\GreenEnergyHub.Charges.FunctionHost\\bin\\Release\\net5.0'
    runs-on: 'windows-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
              
      - name: Install .NET 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
              
      - name: Install .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Azurite ${{ env.AZURITE_VERSION }}
        run: npm install -g azurite@${{ env.AZURITE_VERSION }}

      - name: Install Azure Functions Core Tools ${{ env.AZURE_FUNCTIONS_CORE_TOOLS_VERSION }}
        run: npm install -g azure-functions-core-tools@${{ env.AZURE_FUNCTIONS_CORE_TOOLS_VERSION }}

      - name: Test
        shell: bash
        run: dotnet test --configuration Release ${{ inputs.SOLUTION_FILE_PATH }}

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          fail_ci_if_error: true
          verbose: true
