name: Work with azure login

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  
jobs:
  azure:
    runs-on: windows-latest
    steps:
      - name: Login with azure cli
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_SPN_ID_OIDC }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: List keyvault secrets
        run: az keyvault secret list --id https://kv-secrets-u-002.vault.azure.net/
  
      - name: List keyvault urls
        run: az keyvault key list --id https://kv-datahub-u-002.vault.azure.net/
