name: Infrastructure CD
description: Composite action for deploying infrastructure to a single environment specified by inputs

inputs:
  environment_short:
    required: true
  environment_long:
    required: true
  environment_name:
    required: true
  notification_email:
    required: true
  shared_resources_keyvault_name:
    required: true
  shared_resources_resource_group_name:
    required: true
  shared_resources_sql_server_name:
    required: true
  pat_token:
    required: true
  tenant_id:
    required: true
  spn_id:
    required: true
  spn_object_id:
    required: true
  spn_secret:
    required: true
  subscription_id:
    required: true

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_wrapper: false
        terraform_version: 0.14.10

    - name: Setup domain specific Terraform options
      uses: ./.github/actions/setup-terraform-options
      with:
        notification_email: ${{ inputs.notification_email }}

    - name: Terraform CD
      uses: ./.github/actions/terraform-cd
      with:
        SECRETS_SHARED_RESOURCES_KEYVAULT_NAME: ${{ inputs.shared_resources_keyvault_name }}
        SECRETS_SHARED_RESOURCES_RESOURCE_GROUP_NAME: ${{ inputs.shared_resources_resource_group_name }}
        SECRETS_SHARED_RESOURCES_SQL_SERVER_NAME: ${{ inputs.shared_resources_sql_server_name }}
        SECRETS_PAT_TOKEN: ${{ inputs.pat_token }}
        SECRETS_TENANT_ID: ${{ inputs.tenant_id }}
        SECRETS_SPN_ID: ${{ inputs.spn_id }}
        SECRETS_SPN_OBJECT_ID: ${{ inputs.spn_object_id }}
        SECRETS_SPN_SECRET: ${{ inputs.spn_secret }}
        SECRETS_SUBSCRIPTION_ID: ${{ inputs.subscription_id }}
        PROJECT_NAME: ${{ env.PROJECT_NAME }}
        ORGANISATION_NAME: ${{ env.ORGANISATION_NAME }}
        ENVIRONMENT_SHORT: ${{ inputs.environment_short }}
        ENVIRONMENT_LONG: ${{ inputs.environment_long }}
        ENVIRONMENT_NAME: ${{ inputs.environment_name }}
        TERRAFORM_BACKEND_FILE_PATH: "./build/infrastructure/main/backend.tf"

    - name: Obtain Terraform output
      uses: ./.github/actions/obtain-terraform-output
      id: terraform

    - name: Applying charges migrations
      uses: ./.github/actions/charges-apply-db-migrations
      with:
        sql-connection-string-keyvaultsecretname: ${{ steps.terraform.outputs.sql-connection-string-keyvaultsecretname }}
        keyvault-name: ${{ steps.terraform.outputs.kv-charges-name }}
        environment-name: ${{ inputs.environment_name }}
